### PR TITLE
opts.avoidTryMergingArray

### PR DESCRIPTION
**Pull request by jabiinfante**
Hello,

I have found a behaviour which might want to be overridden sometimes.

Right now, when using "ignoreKeys" or "hardMergeKeys" and those keys are containing arrays, the library will try to merge (and sometimes successfully) those values on the array:

```
t.deepEqual(
    mergeAdvanced(
      {
        c: [1, 2, 3],
      },
      {
        c: [4, 5, 6],
      },
      {
        ignoreKeys: ['c'],
      },
    ),
    {
      c: [1, 2, 3, 4, 5, 6],
    },
    '',
  )
```

Allthought that might be a desired behaviour (most?) of the times, maybe on those cases, we might want to keep array values as on `input1` (ignoreKeys) or as on `input2`  (hardMergeKeys).

I have come out with the **opt.avoidTryMergingArray** which will behave as I just explained (and as described on tests '19.01')...

Maybe the name is not too clear?

### CODE REVIEW

**Comment by revelt** [comment]
Wait, in arrays case, one-way (unidirectional) merging **should** respect the `opts. ignoreKeys` and `opts.hardMergeKeys` settings:

```js
t.deepEqual(
    mergeAdvanced(
      {
        c: [1, 2, 3],
      },
      {
        c: [4, 5, 6],
      },
      {
        ignoreKeys: ['c'],
      },
    ),
    {
      c: [1, 2, 3],
    },
    '',
  )
```

and 


```js
t.deepEqual(
    mergeAdvanced(
      {
        c: [1, 2, 3],
      },
      {
        c: [4, 5, 6],
      },
      {
        hardMergeKeys: ['c'],
      },
    ),
    {
      c: [4, 5, 6],
    },
    '',
  )
```

If so, we don't even need the `opts. avoidTryMergingArray ` setting?

To me it looks like `opts. ignoreKeys` and `opts.hardMergeKeys` needs to be completed to work with arrays? What do you think?

**Comment by jabiinfante** [comment]
Yes, I thought that would be the expected behaviour.
So i have tried to remove  "&& (!isArr(i2)" from lines [73](https://github.com/codsen/object-merge-advanced/blob/master/src/main.js#L73) and [75](https://github.com/codsen/object-merge-advanced/blob/master/src/main.js#L75)


But then test 14.01.03 broke:

 ✖ 14.01 - objects within arrays 14.01.03 - hard merge * - does nothing different because keys are not clashing
```
  t.deepEqual(
    mergeAdvanced(
      {
        a: [
          {
            b: 'zzz',
            c: 'ccc', // <----- this key is unique.
          },
        ],
      },
      {
        a: [
          {
            b: false,
            d: 'ddd', // <----- and this key is unique.
          },
        ],
      },
      {
        hardMergeKeys: '*', // <----- notice it's glob
      },
    ),
    {
      a: [
        {
          b: 'zzz',
          c: 'ccc',
        },
        {
          b: false,
          d: 'ddd',
        },
      ],
    },
    '14.01.03 - hard merge * - does nothing different because keys are not clashing',
    // the problem is, hard merges drive key-vs.-key choice and here without
    // opts.mergeObjectsOnlyWhenKeysetMatches: false
    // the objects are not merged since they have unique keys.
    // Their parent arrays are contatenated instead.
  )
```
(that's why if decided to get that option set up)..

maybe the test should be rewritten with something like this:
```
  t.deepEqual(
    mergeAdvanced(
      {
        a: [
          {
            b: 'zzz',
            c: 'ccc', // <----- this key is unique.
          },
        ],
      },
      {
        a: [
          {
            b: false,
            d: 'ddd', // <----- and this key is unique.
          },
        ],
      },
      {
        hardMergeKeys: '*', // <----- notice it's glob
      },
    ),
    {
      a: [
        {
          b: false,
          d: 'ddd', // <----- and this key is unique.
        },
      ],
    },
    '14.01.03 - hard merge * - does nothing different because keys are not clashing',
    // the problem is, hard merges drive key-vs.-key choice and here without
    // opts.mergeObjectsOnlyWhenKeysetMatches: false
    // the objects are not merged since they have unique keys.
    // Their parent arrays are contatenated instead.
  )
```

Makes sense to me, but it would broke previous behaviour.

**Comment by revelt** [comment]
Yeah, I agree, `hardMergeKeys` should hard-merge for real, no matter what's the value. I guess we'll have to bump major and adjust 14.01.03 accordingly.

I'd then add unit tests for all 10 possible types of values as a plain object value and then merge with opts as a) ignore and b) hardMerge on both c) root within object and d) deeper levels within object, then e) within array and f) object-within-array-within-object level. That's around 80 unit test comparisons.

I'm up for amending 14.01.03 and implementing the one-way merges properly. What do you think?

**Comment by jabiinfante** [comment]
Looks good to me ;)
thank you @revelt

**Comment by revelt** [comment]
@jabiinfante `v9.0.0` fixes the hard merges, both ways, please review

**Pull request closed without merging**
